market:
    dataset: '365_days_60_seconds'
    window: 
        - '2022-02-01'
        - '2022-03-01'
    markets: 
        - 'BTC_USD'
    features:
        - 'nothing yet'

wallet:
    balances:
        USD: 10000

broker:
    fee: 0.0018

investor:
    class: "BernoulliInvestor"
    p:
        - 0.5
        - 0.5