market:
    window_size: 3
    resolution: 300
    ob_depth: 20
    markets: 
        - 'BTC_USD'
        - 'ETH_BTC'
    features:
        EMA:
            alpha: 1.2
            N: 10

wallet:
    subaccount: 'geezer'
    balance: 100

broker:
    fee: 0.0018

investor:
    class: "BernoulliInvestor"
    p:
        - 0.5
        - 0.5